# @package _global_
defaults:
  - _self_

openai_api_key: sk-proj-tSo2Jj0SSFbpSnl9fr1eT3BlbkFJfZ44EwKaTZVCQquujGbr

model_name: gpt-3.5-turbo
max_context_length: 4096
exllama: False

system_tag_start: "<|im_start|>system"
system_tag_end: "<|im_end|>"

user_tag_start: "<|im_start|>user"
user_tag_end: "<|im_end|>"

ai_tag_start: "<|im_start|>assistant"
ai_tag_end: "<|im_end|>"

stop_words:
- "USER:"
- "ASSISTANT:"
